name: ML CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        run: |
          echo "Running training script..."
          python -u train.py

      - name: Validate training output
        run: |
          python -c "
      import os
      assert os.path.exists('best_model.pkl'), 'Model not created!'
      print('Model exists ✔')
      "